### ISSUE TITLE
Log in issue

### ISSUE THREAD

**Issue by suyashkumar2409** [suyashkumar2409/table-topics#5]
Currently, trying to log in with non existing email id returns empty response @Aman-15 do you want to solve this?

**Comment by Aman-15** [comment]
With the change in the database from postgres to sqlite3, I am not getting any empty response. However, I am not able to login after a signing up:

Login : Error in getting user sql: Scan error on column index 0: converting driver.Value type <nil> ("<nil>") to a int64: invalid syntax

The user Id field is null for every user I add.

**Comment by Aman-15** [comment]
Check if user is nil or not, before accessing password field in route.Authenticate (route.auth.go)
